resources:
 repositories:
 - repository: MyShuttle
   name: learnazure4641/MyShuttle
   type: github
   endpoint: learnazure4641
   
 - repository: PartsUnlimited
   name: learnazure4641/PartsUnlimited
   type: github
   endpoint: learnazure4641

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
  
steps:
- script: yum install tomcat9 -y
- checkout: MyShuttle
- checkout: PartsUnlimited
