resources:
 repositories:
 - repository: MyShuttle
   name: learnazure4641/MyShuttle
   type: github
   endpoint: learnazure4641
   
 - repository: PartsUnlimited
   name: learnazure4641/PartsUnlimited
   type: github
   endpoint: learnazure4641

trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: BuildMaven
  jobs:
  - job: MavenBuild
    displayName: MavenBuild
    
    steps:
    - checkout: MyShuttle
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false