resources:
 repositories:
 - repository: MyShuttle
   name: learnazure4641/MyShuttle
   type: github
   endpoint: learnazure4641
   
 - repository: PartsUnlimited
   name: learnazure4641/PartsUnlimited
   type: github
   endpoint: learnazure4641

schedules:
  - cron: "00 14 * * Fri"
    displayName: Build at 6:30 PM IST on Friday
    branches:
      include:
        - main
stages:
- stage: BuildMaven
  
  jobs:
  - job: MavenBuild
    pool:
      vmImage: ubuntu-latest
    displayName: MavenBuild
    
    steps:
    - checkout: MyShuttle
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(agent.builddirectory)'
        Contents: '**/target/*.war'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: BuildDOTNET
  jobs:
  - job: Builddotnet
    pool:
      vmImage: 'windows-2019'
    displayName: PartsUnlimited
    steps:
      - checkout: PartsUnlimited
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
          platform: 'Any CPU'
          configuration: 'Release'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'